export var DataJson = `
{
  "Coral Classification Survey": {
    "Citation": "### TO DO ###",
    "Description": "Placeholder text.",
    "Time Period of Content": "1/1/2006 - 17/06/2023",
    "Spatial Domain": "Placeholder text.",
    "Keywords": "Placeholder text.",
    "Access Constraints": "Placeholder text.",
    "Use Constraints": "Placeholder text.",
    "Point of Contact": "Placeholder text.",
    "Browse Graphic": "Placeholder text.",
    "Data Set Credit - Where Credited": "Placeholder text.",
    "Data Set Size at Reception": "Placeholder text.",
    "Data Category": "Marine Life & Habitats",
    "Indirect Spatial Reference": "Placeholder text.",
    "Direct Spatial Reference": "Placeholder text.",
    "Point and Vector Object Information": "Placeholder text.",
    "Horizontal Coordinate System Definition": "Placeholder text.",
    "Vertical Coordinate System Definition": "Placeholder text.",
    "Detailed Description": "Placeholder text.",
    "Overview Description": "Placeholder text.",
    "Data Custodian": "Placeholder text.",
    "Resource Description": "Placeholder text.",
    "Standard Order Process": "Placeholder text.",
    "Technical Prerequisites": "Placeholder text.",
    "Metadata Date": "Placeholder text.",
    "Metadata Standard Name": "Placeholder text.",
    "Metadata Standard Version": "Placeholder text.",
    "Metadata Time Conversion": "Placeholder text.",
    "Available in Platform": "Placeholder text.",
    "External Metadata Reference": "Placeholder text."
  },
  "Fish & Invertebrate Abundance Survey": {
    "Citation": "### TO DO ###",
    "Description": "Placeholder text.",
    "Time Period of Content": "2007-2023",
    "Spatial Domain": "Placeholder text.",
    "Keywords": "Placeholder text.",
    "Access Constraints": "Placeholder text.",
    "Use Constraints": "Placeholder text.",
    "Point of Contact": "Placeholder text.",
    "Browse Graphic": "Placeholder text.",
    "Data Set Credit - Where Credited": "Placeholder text.",
    "Data Set Size at Reception": "Placeholder text.",
    "Data Category": "Marine Life & Habitats",
    "Indirect Spatial Reference": "Placeholder text.",
    "Direct Spatial Reference": "Placeholder text.",
    "Point and Vector Object Information": "Placeholder text.",
    "Horizontal Coordinate System Definition": "Placeholder text.",
    "Vertical Coordinate System Definition": "Placeholder text.",
    "Detailed Description": "Placeholder text.",
    "Overview Description": "Placeholder text.",
    "Data Custodian": "Placeholder text.",
    "Resource Description": "Placeholder text.",
    "Standard Order Process": "Placeholder text.",
    "Technical Prerequisites": "Placeholder text.",
    "Metadata Date": "Placeholder text.",
    "Metadata Standard Name": "Placeholder text.",
    "Metadata Standard Version": "Placeholder text.",
    "Metadata Time Conversion": "Placeholder text.",
    "Available in Platform": "Placeholder text.",
    "External Metadata Reference": "Placeholder text."
  },
  "Shipping and Boating Channels": {
    "Citation": "### TO DO ###",
    "Description": "Placeholder text.",
    "Time Period of Content": "2018",
    "Spatial Domain": "Placeholder text.",
    "Keywords": "Placeholder text.",
    "Access Constraints": "Placeholder text.",
    "Use Constraints": "Placeholder text.",
    "Point of Contact": "Placeholder text.",
    "Browse Graphic": "Placeholder text.",
    "Data Set Credit - Where Credited": "Placeholder text.",
    "Data Set Size at Reception": "Placeholder text.",
    "Data Category": "Human Use & Users",
    "Indirect Spatial Reference": "Placeholder text.",
    "Direct Spatial Reference": "Placeholder text.",
    "Point and Vector Object Information": "Placeholder text.",
    "Horizontal Coordinate System Definition": "Placeholder text.",
    "Vertical Coordinate System Definition": "Placeholder text.",
    "Detailed Description": "Placeholder text.",
    "Overview Description": "Placeholder text.",
    "Data Custodian": "Placeholder text.",
    "Resource Description": "Placeholder text.",
    "Standard Order Process": "Placeholder text.",
    "Technical Prerequisites": "Placeholder text.",
    "Metadata Date": "Placeholder text.",
    "Metadata Standard Name": "Placeholder text.",
    "Metadata Standard Version": "Placeholder text.",
    "Metadata Time Conversion": "Placeholder text.",
    "Available in Platform": "Placeholder text.",
    "External Metadata Reference": "Placeholder text."
  },
  "Boating Activity": {
    "Citation": "### TO DO ###",
    "Description": "Placeholder text.",
    "Time Period of Content": "23/07/2016 - 26/02/2023",
    "Spatial Domain": "Placeholder text.",
    "Keywords": "Placeholder text.",
    "Access Constraints": "Placeholder text.",
    "Use Constraints": "Placeholder text.",
    "Point of Contact": "Placeholder text.",
    "Browse Graphic": "Placeholder text.",
    "Data Set Credit - Where Credited": "Placeholder text.",
    "Data Set Size at Reception": "Placeholder text.",
    "Data Category": "Human Use & Users",
    "Indirect Spatial Reference": "Placeholder text.",
    "Direct Spatial Reference": "Placeholder text.",
    "Point and Vector Object Information": "Placeholder text.",
    "Horizontal Coordinate System Definition": "Placeholder text.",
    "Vertical Coordinate System Definition": "Placeholder text.",
    "Detailed Description": "Placeholder text.",
    "Overview Description": "Placeholder text.",
    "Data Custodian": "Placeholder text.",
    "Resource Description": "Placeholder text.",
    "Standard Order Process": "Placeholder text.",
    "Technical Prerequisites": "Placeholder text.",
    "Metadata Date": "Placeholder text.",
    "Metadata Standard Name": "Placeholder text.",
    "Metadata Standard Version": "Placeholder text.",
    "Metadata Time Conversion": "Placeholder text.",
    "Available in Platform": "Placeholder text.",
    "External Metadata Reference": "Placeholder text."
  },
  "Moreton Bay Social Values Survey": {
    "Citation": "### TO DO ###",
    "Description": "Placeholder text.",
    "Time Period of Content": "2023",
    "Spatial Domain": "Placeholder text.",
    "Keywords": "Placeholder text.",
    "Access Constraints": "Placeholder text.",
    "Use Constraints": "Placeholder text.",
    "Point of Contact": "Placeholder text.",
    "Browse Graphic": "Placeholder text.",
    "Data Set Credit - Where Credited": "Placeholder text.",
    "Data Set Size at Reception": "Placeholder text.",
    "Data Category": "Human Use & Users",
    "Indirect Spatial Reference": "Placeholder text.",
    "Direct Spatial Reference": "Placeholder text.",
    "Point and Vector Object Information": "Placeholder text.",
    "Horizontal Coordinate System Definition": "Placeholder text.",
    "Vertical Coordinate System Definition": "Placeholder text.",
    "Detailed Description": "Placeholder text.",
    "Overview Description": "Placeholder text.",
    "Data Custodian": "Placeholder text.",
    "Resource Description": "Placeholder text.",
    "Standard Order Process": "Placeholder text.",
    "Technical Prerequisites": "Placeholder text.",
    "Metadata Date": "Placeholder text.",
    "Metadata Standard Name": "Placeholder text.",
    "Metadata Standard Version": "Placeholder text.",
    "Metadata Time Conversion": "Placeholder text.",
    "Available in Platform": "Placeholder text.",
    "External Metadata Reference": "Placeholder text."
  },
  "Seagrass Extent Map 2004": {
    "Citation": "Roelfsema, Christiaan M; Kovacs, Eva M; Moffatt, David; Phinn, Stuart R; Hoseck, Steve (2015): Habitat map of seagrass cover derived from a supervised moderate-spatial-resolution multi-spectral satellite image, integrated with manual delineation and coincident field data, Moreton Bay, 2011, with link to shapefile [dataset]. PANGAEA, https://doi.org/10.1594/PANGAEA.846271",
    "Description": "Placeholder text.",
    "Time Period of Content": "2004",
    "Spatial Domain": "Placeholder text.",
    "Keywords": "Placeholder text.",
    "Access Constraints": "Placeholder text.",
    "Use Constraints": "Placeholder text.",
    "Point of Contact": "Placeholder text.",
    "Browse Graphic": "Placeholder text.",
    "Data Set Credit - Where Credited": "Placeholder text.",
    "Data Set Size at Reception": "Placeholder text.",
    "Data Category": "Marine Life & Habitats",
    "Indirect Spatial Reference": "Placeholder text.",
    "Direct Spatial Reference": "Placeholder text.",
    "Point and Vector Object Information": "Placeholder text.",
    "Horizontal Coordinate System Definition": "Placeholder text.",
    "Vertical Coordinate System Definition": "Placeholder text.",
    "Detailed Description": "Placeholder text.",
    "Overview Description": "Placeholder text.",
    "Data Custodian": "Placeholder text.",
    "Resource Description": "Placeholder text.",
    "Standard Order Process": "Placeholder text.",
    "Technical Prerequisites": "Placeholder text.",
    "Metadata Date": "Placeholder text.",
    "Metadata Standard Name": "Placeholder text.",
    "Metadata Standard Version": "Placeholder text.",
    "Metadata Time Conversion": "Placeholder text.",
    "Available in Platform": "Placeholder text.",
    "External Metadata Reference": "Placeholder text."
  },
  "Seagrass Extent Map 2011": {
    "Citation": "Roelfsema, Christiaan M; Kovacs, Eva M; Moffatt, David; Phinn, Stuart R; Hoseck, Steve (2015): Habitat map of seagrass cover derived from a supervised moderate-spatial-resolution multi-spectral satellite image, integrated with manual delineation and coincident field data, Moreton Bay, 2011, with link to shapefile [dataset]. PANGAEA, https://doi.org/10.1594/PANGAEA.846271",
    "Description": "Placeholder text.",
    "Time Period of Content": "2011",
    "Spatial Domain": "Placeholder text.",
    "Keywords": "Placeholder text.",
    "Access Constraints": "Placeholder text.",
    "Use Constraints": "Placeholder text.",
    "Point of Contact": "Placeholder text.",
    "Browse Graphic": "Placeholder text.",
    "Data Set Credit - Where Credited": "Placeholder text.",
    "Data Set Size at Reception": "Placeholder text.",
    "Data Category": "Marine Life & Habitats",
    "Indirect Spatial Reference": "Placeholder text.",
    "Direct Spatial Reference": "Placeholder text.",
    "Point and Vector Object Information": "Placeholder text.",
    "Horizontal Coordinate System Definition": "Placeholder text.",
    "Vertical Coordinate System Definition": "Placeholder text.",
    "Detailed Description": "Placeholder text.",
    "Overview Description": "Placeholder text.",
    "Data Custodian": "Placeholder text.",
    "Resource Description": "Placeholder text.",
    "Standard Order Process": "Placeholder text.",
    "Technical Prerequisites": "Placeholder text.",
    "Metadata Date": "Placeholder text.",
    "Metadata Standard Name": "Placeholder text.",
    "Metadata Standard Version": "Placeholder text.",
    "Metadata Time Conversion": "Placeholder text.",
    "Available in Platform": "Placeholder text.",
    "External Metadata Reference": "Placeholder text."
  },
  "Seagrass Extent Map 2015": {
    "Citation": "Kovacs, Eva M; Roelfsema, Christiaan M; Phinn, Stuart R; Lyons, Mitchell; Udy, James; Baltais, Simon (2021): Seagrass cover map for the optically complex waters of Moreton Bay, Queensland, Australia (2015) XXX [dataset]. PANGAEA, https://doi.org/10.1594/PANGAEA.937501",
    "Description": "Placeholder text.",
    "Time Period of Content": "2015",
    "Spatial Domain": "Placeholder text.",
    "Keywords": "Placeholder text.",
    "Access Constraints": "Placeholder text.",
    "Use Constraints": "Placeholder text.",
    "Point of Contact": "Placeholder text.",
    "Browse Graphic": "Placeholder text.",
    "Data Set Credit - Where Credited": "Placeholder text.",
    "Data Set Size at Reception": "Placeholder text.",
    "Data Category": "Marine Life & Habitats",
    "Indirect Spatial Reference": "Placeholder text.",
    "Direct Spatial Reference": "Placeholder text.",
    "Point and Vector Object Information": "Placeholder text.",
    "Horizontal Coordinate System Definition": "Placeholder text.",
    "Vertical Coordinate System Definition": "Placeholder text.",
    "Detailed Description": "Placeholder text.",
    "Overview Description": "Placeholder text.",
    "Data Custodian": "Placeholder text.",
    "Resource Description": "Placeholder text.",
    "Standard Order Process": "Placeholder text.",
    "Technical Prerequisites": "Placeholder text.",
    "Metadata Date": "Placeholder text.",
    "Metadata Standard Name": "Placeholder text.",
    "Metadata Standard Version": "Placeholder text.",
    "Metadata Time Conversion": "Placeholder text.",
    "Available in Platform": "Placeholder text.",
    "External Metadata Reference": "Placeholder text."
  },
  "Wetland Extent Classifications": {
    "Citation": "### TO DO ###",
    "Description": "Placeholder text.",
    "Time Period of Content": "16/07/2007",
    "Spatial Domain": "Placeholder text.",
    "Keywords": "Placeholder text.",
    "Access Constraints": "Placeholder text.",
    "Use Constraints": "Placeholder text.",
    "Point of Contact": "Placeholder text.",
    "Browse Graphic": "Placeholder text.",
    "Data Set Credit - Where Credited": "Placeholder text.",
    "Data Set Size at Reception": "Placeholder text.",
    "Data Category": "Marine Life & Habitats",
    "Indirect Spatial Reference": "Placeholder text.",
    "Direct Spatial Reference": "Placeholder text.",
    "Point and Vector Object Information": "Placeholder text.",
    "Horizontal Coordinate System Definition": "Placeholder text.",
    "Vertical Coordinate System Definition": "Placeholder text.",
    "Detailed Description": "Placeholder text.",
    "Overview Description": "Placeholder text.",
    "Data Custodian": "Placeholder text.",
    "Resource Description": "Placeholder text.",
    "Standard Order Process": "Placeholder text.",
    "Technical Prerequisites": "Placeholder text.",
    "Metadata Date": "Placeholder text.",
    "Metadata Standard Name": "Placeholder text.",
    "Metadata Standard Version": "Placeholder text.",
    "Metadata Time Conversion": "Placeholder text.",
    "Available in Platform": "Placeholder text.",
    "External Metadata Reference": "Placeholder text."
  },
  "Satellite Mosaic of Moreton Bay 2018": {
    "Citation": "Allen Coral Atlas (2020). Imagery, maps and monitoring of the world's tropical coral reefs. doi.org/10.5281/zenodo.3833242 Allen Coral Atlas maps, bathymetry and map statistics are � 2020 Allen Coral Atlas Partnership and Vulcan, Inc. and are licensed CC BY 4.0 (https://creativecommons.org/licenses/by/4.0/) The Satellite Coral Reef Mosaic is � 2020 Planet Labs and licensed CC BY-SA-NC 4.0 (https://creativecommons.org/licenses/by-nc-sa/4.0/)",
    "Description": "Placeholder text.",
    "Time Period of Content": "2018",
    "Spatial Domain": "Placeholder text.",
    "Keywords": "Placeholder text.",
    "Access Constraints": "Placeholder text.",
    "Use Constraints": "Placeholder text.",
    "Point of Contact": "Placeholder text.",
    "Browse Graphic": "Placeholder text.",
    "Data Set Credit - Where Credited": "Placeholder text.",
    "Data Set Size at Reception": "Placeholder text.",
    "Data Category": "Environmental Change & Monitoring",
    "Indirect Spatial Reference": "Placeholder text.",
    "Direct Spatial Reference": "Placeholder text.",
    "Point and Vector Object Information": "Placeholder text.",
    "Horizontal Coordinate System Definition": "Placeholder text.",
    "Vertical Coordinate System Definition": "Placeholder text.",
    "Detailed Description": "Placeholder text.",
    "Overview Description": "Placeholder text.",
    "Data Custodian": "Placeholder text.",
    "Resource Description": "Placeholder text.",
    "Standard Order Process": "Placeholder text.",
    "Technical Prerequisites": "Placeholder text.",
    "Metadata Date": "Placeholder text.",
    "Metadata Standard Name": "Placeholder text.",
    "Metadata Standard Version": "Placeholder text.",
    "Metadata Time Conversion": "Placeholder text.",
    "Available in Platform": "Placeholder text.",
    "External Metadata Reference": "Placeholder text."
  },
  "Satellite Mosaic of Moreton Bay 2019": {
    "Citation": "Allen Coral Atlas (2020). Imagery, maps and monitoring of the world's tropical coral reefs. doi.org/10.5281/zenodo.3833242 Allen Coral Atlas maps, bathymetry and map statistics are � 2020 Allen Coral Atlas Partnership and Vulcan, Inc. and are licensed CC BY 4.0 (https://creativecommons.org/licenses/by/4.0/) The Satellite Coral Reef Mosaic is � 2020 Planet Labs and licensed CC BY-SA-NC 4.0 (https://creativecommons.org/licenses/by-nc-sa/4.0/)",
    "Description": "Placeholder text.",
    "Time Period of Content": "2019",
    "Spatial Domain": "Placeholder text.",
    "Keywords": "Placeholder text.",
    "Access Constraints": "Placeholder text.",
    "Use Constraints": "Placeholder text.",
    "Point of Contact": "Placeholder text.",
    "Browse Graphic": "Placeholder text.",
    "Data Set Credit - Where Credited": "Placeholder text.",
    "Data Set Size at Reception": "Placeholder text.",
    "Data Category": "Environmental Change & Monitoring",
    "Indirect Spatial Reference": "Placeholder text.",
    "Direct Spatial Reference": "Placeholder text.",
    "Point and Vector Object Information": "Placeholder text.",
    "Horizontal Coordinate System Definition": "Placeholder text.",
    "Vertical Coordinate System Definition": "Placeholder text.",
    "Detailed Description": "Placeholder text.",
    "Overview Description": "Placeholder text.",
    "Data Custodian": "Placeholder text.",
    "Resource Description": "Placeholder text.",
    "Standard Order Process": "Placeholder text.",
    "Technical Prerequisites": "Placeholder text.",
    "Metadata Date": "Placeholder text.",
    "Metadata Standard Name": "Placeholder text.",
    "Metadata Standard Version": "Placeholder text.",
    "Metadata Time Conversion": "Placeholder text.",
    "Available in Platform": "Placeholder text.",
    "External Metadata Reference": "Placeholder text."
  },
  "Satellite Mosaic of Moreton Bay 2020": {
    "Citation": "Allen Coral Atlas (2020). Imagery, maps and monitoring of the world's tropical coral reefs. doi.org/10.5281/zenodo.3833242 Allen Coral Atlas maps, bathymetry and map statistics are � 2020 Allen Coral Atlas Partnership and Vulcan, Inc. and are licensed CC BY 4.0 (https://creativecommons.org/licenses/by/4.0/) The Satellite Coral Reef Mosaic is � 2020 Planet Labs and licensed CC BY-SA-NC 4.0 (https://creativecommons.org/licenses/by-nc-sa/4.0/)",
    "Description": "Placeholder text.",
    "Time Period of Content": "2020",
    "Spatial Domain": "Placeholder text.",
    "Keywords": "Placeholder text.",
    "Access Constraints": "Placeholder text.",
    "Use Constraints": "Placeholder text.",
    "Point of Contact": "Placeholder text.",
    "Browse Graphic": "Placeholder text.",
    "Data Set Credit - Where Credited": "Placeholder text.",
    "Data Set Size at Reception": "Placeholder text.",
    "Data Category": "Environmental Change & Monitoring",
    "Indirect Spatial Reference": "Placeholder text.",
    "Direct Spatial Reference": "Placeholder text.",
    "Point and Vector Object Information": "Placeholder text.",
    "Horizontal Coordinate System Definition": "Placeholder text.",
    "Vertical Coordinate System Definition": "Placeholder text.",
    "Detailed Description": "Placeholder text.",
    "Overview Description": "Placeholder text.",
    "Data Custodian": "Placeholder text.",
    "Resource Description": "Placeholder text.",
    "Standard Order Process": "Placeholder text.",
    "Technical Prerequisites": "Placeholder text.",
    "Metadata Date": "Placeholder text.",
    "Metadata Standard Name": "Placeholder text.",
    "Metadata Standard Version": "Placeholder text.",
    "Metadata Time Conversion": "Placeholder text.",
    "Available in Platform": "Placeholder text.",
    "External Metadata Reference": "Placeholder text."
  },
  "Reef Extent Map": {
    "Citation": "Roelfsema, Christiaan M; Loder, Jennifer; Host, Rachel; Kovacs, Eva M (2018): Benthic inventory of reefal areas in Moreton Bay, Australia [dataset]. PANGAEA, https://doi.org/10.1594/PANGAEA.892402",
    "Description": "Placeholder text.",
    "Time Period of Content": "2014",
    "Spatial Domain": "Placeholder text.",
    "Keywords": "Placeholder text.",
    "Access Constraints": "Placeholder text.",
    "Use Constraints": "Placeholder text.",
    "Point of Contact": "Placeholder text.",
    "Browse Graphic": "Placeholder text.",
    "Data Set Credit - Where Credited": "Placeholder text.",
    "Data Set Size at Reception": "Placeholder text.",
    "Data Category": "Marine Life & Habitats",
    "Indirect Spatial Reference": "Placeholder text.",
    "Direct Spatial Reference": "Placeholder text.",
    "Point and Vector Object Information": "Placeholder text.",
    "Horizontal Coordinate System Definition": "Placeholder text.",
    "Vertical Coordinate System Definition": "Placeholder text.",
    "Detailed Description": "Placeholder text.",
    "Overview Description": "Placeholder text.",
    "Data Custodian": "Placeholder text.",
    "Resource Description": "Placeholder text.",
    "Standard Order Process": "Placeholder text.",
    "Technical Prerequisites": "Placeholder text.",
    "Metadata Date": "Placeholder text.",
    "Metadata Standard Name": "Placeholder text.",
    "Metadata Standard Version": "Placeholder text.",
    "Metadata Time Conversion": "Placeholder text.",
    "Available in Platform": "Placeholder text.",
    "External Metadata Reference": "Placeholder text."
  },
  "Benthic Inventory of Moreton Bay Reefs": {
    "Citation": "Roelfsema, Christiaan M; Loder, Jennifer; Host, Rachel; Kovacs, Eva M (2018): Benthic inventory of reefal areas in Moreton Bay, Australia [dataset]. PANGAEA, https://doi.org/10.1594/PANGAEA.892402",
    "Description": "Placeholder text.",
    "Time Period of Content": "2016",
    "Spatial Domain": "Placeholder text.",
    "Keywords": "Placeholder text.",
    "Access Constraints": "Placeholder text.",
    "Use Constraints": "Placeholder text.",
    "Point of Contact": "Placeholder text.",
    "Browse Graphic": "Placeholder text.",
    "Data Set Credit - Where Credited": "Placeholder text.",
    "Data Set Size at Reception": "Placeholder text.",
    "Data Category": "Marine Life & Habitats",
    "Indirect Spatial Reference": "Placeholder text.",
    "Direct Spatial Reference": "Placeholder text.",
    "Point and Vector Object Information": "Placeholder text.",
    "Horizontal Coordinate System Definition": "Placeholder text.",
    "Vertical Coordinate System Definition": "Placeholder text.",
    "Detailed Description": "Placeholder text.",
    "Overview Description": "Placeholder text.",
    "Data Custodian": "Placeholder text.",
    "Resource Description": "Placeholder text.",
    "Standard Order Process": "Placeholder text.",
    "Technical Prerequisites": "Placeholder text.",
    "Metadata Date": "Placeholder text.",
    "Metadata Standard Name": "Placeholder text.",
    "Metadata Standard Version": "Placeholder text.",
    "Metadata Time Conversion": "Placeholder text.",
    "Available in Platform": "Placeholder text.",
    "External Metadata Reference": "Placeholder text."
  },
  "Marine Acoustic Telemetry Data": {
    "Citation": "Hoenner X, Huveneers C, Steckenreuter A, Simpfendorfer C, Tattersall K, Jaine F, Atkins N, Babcock R, Brodie S, Burgess J, Campbell H, Heupel M, Pasquer P, Proctor R, Taylor MD, Udyawer V, Harcourt R (2017), Australia's continental-scale acoustic tracking database and its automated quality control process. Australian Ocean Data Network - DOI: 10.4225/69/5979810a7dd6f (http://dx.doi.org/10.4225/69/5979810a7dd6f)",
    "Description": "Placeholder text.",
    "Time Period of Content": "2009-2015",
    "Spatial Domain": "Placeholder text.",
    "Keywords": "Placeholder text.",
    "Access Constraints": "Placeholder text.",
    "Use Constraints": "Placeholder text.",
    "Point of Contact": "Placeholder text.",
    "Browse Graphic": "Placeholder text.",
    "Data Set Credit - Where Credited": "Placeholder text.",
    "Data Set Size at Reception": "Placeholder text.",
    "Data Category": "Marine Life & Habitats",
    "Indirect Spatial Reference": "Placeholder text.",
    "Direct Spatial Reference": "Placeholder text.",
    "Point and Vector Object Information": "Placeholder text.",
    "Horizontal Coordinate System Definition": "Placeholder text.",
    "Vertical Coordinate System Definition": "Placeholder text.",
    "Detailed Description": "Placeholder text.",
    "Overview Description": "Placeholder text.",
    "Data Custodian": "Placeholder text.",
    "Resource Description": "Placeholder text.",
    "Standard Order Process": "Placeholder text.",
    "Technical Prerequisites": "Placeholder text.",
    "Metadata Date": "Placeholder text.",
    "Metadata Standard Name": "Placeholder text.",
    "Metadata Standard Version": "Placeholder text.",
    "Metadata Time Conversion": "Placeholder text.",
    "Available in Platform": "Placeholder text.",
    "External Metadata Reference": "Placeholder text."
  },
  "Moreton Bay Broadscale Habitats": {
    "Citation": "� State of Queensland (Department of Environment and Science) 2023. Updated data available at http://qldspatial.information.qld.gov.au/catalogue//.",
    "Description": "Placeholder text.",
    "Time Period of Content": "12/09/2007-02/12/2007",
    "Spatial Domain": "Placeholder text.",
    "Keywords": "Placeholder text.",
    "Access Constraints": "Placeholder text.",
    "Use Constraints": "Placeholder text.",
    "Point of Contact": "Placeholder text.",
    "Browse Graphic": "Placeholder text.",
    "Data Set Credit - Where Credited": "Placeholder text.",
    "Data Set Size at Reception": "Placeholder text.",
    "Data Category": "Marine Life & Habitats",
    "Indirect Spatial Reference": "Placeholder text.",
    "Direct Spatial Reference": "Placeholder text.",
    "Point and Vector Object Information": "Placeholder text.",
    "Horizontal Coordinate System Definition": "Placeholder text.",
    "Vertical Coordinate System Definition": "Placeholder text.",
    "Detailed Description": "Placeholder text.",
    "Overview Description": "Placeholder text.",
    "Data Custodian": "Placeholder text.",
    "Resource Description": "Placeholder text.",
    "Standard Order Process": "Placeholder text.",
    "Technical Prerequisites": "Placeholder text.",
    "Metadata Date": "Placeholder text.",
    "Metadata Standard Name": "Placeholder text.",
    "Metadata Standard Version": "Placeholder text.",
    "Metadata Time Conversion": "Placeholder text.",
    "Available in Platform": "Placeholder text.",
    "External Metadata Reference": "Placeholder text."
  },
  "Moreton Bay Marine Park Zoning": {
    "Citation": "� State of Queensland (Department of Environment and Science) 2023",
    "Description": "Placeholder text.",
    "Time Period of Content": "03/12/2007-01/03/2009",
    "Spatial Domain": "Placeholder text.",
    "Keywords": "Placeholder text.",
    "Access Constraints": "Placeholder text.",
    "Use Constraints": "Placeholder text.",
    "Point of Contact": "Placeholder text.",
    "Browse Graphic": "Placeholder text.",
    "Data Set Credit - Where Credited": "Placeholder text.",
    "Data Set Size at Reception": "Placeholder text.",
    "Data Category": "Governance & Management",
    "Indirect Spatial Reference": "Placeholder text.",
    "Direct Spatial Reference": "Placeholder text.",
    "Point and Vector Object Information": "Placeholder text.",
    "Horizontal Coordinate System Definition": "Placeholder text.",
    "Vertical Coordinate System Definition": "Placeholder text.",
    "Detailed Description": "Placeholder text.",
    "Overview Description": "Placeholder text.",
    "Data Custodian": "Placeholder text.",
    "Resource Description": "Placeholder text.",
    "Standard Order Process": "Placeholder text.",
    "Technical Prerequisites": "Placeholder text.",
    "Metadata Date": "Placeholder text.",
    "Metadata Standard Name": "Placeholder text.",
    "Metadata Standard Version": "Placeholder text.",
    "Metadata Time Conversion": "Placeholder text.",
    "Available in Platform": "Placeholder text.",
    "External Metadata Reference": "Placeholder text."
  },
  "Moreton Bay Marine Park Boundary": {
    "Citation": "State of Queensland (Department of Environment and Science) 2023. Updated data available at http://qldspatial.information.qld.gov.au/catalogue//.",
    "Description": "Placeholder text.",
    "Time Period of Content": "16/07/2007",
    "Spatial Domain": "Placeholder text.",
    "Keywords": "Placeholder text.",
    "Access Constraints": "Placeholder text.",
    "Use Constraints": "Placeholder text.",
    "Point of Contact": "Placeholder text.",
    "Browse Graphic": "Placeholder text.",
    "Data Set Credit - Where Credited": "Placeholder text.",
    "Data Set Size at Reception": "Placeholder text.",
    "Data Category": "Governance & Management",
    "Indirect Spatial Reference": "Placeholder text.",
    "Direct Spatial Reference": "Placeholder text.",
    "Point and Vector Object Information": "Placeholder text.",
    "Horizontal Coordinate System Definition": "Placeholder text.",
    "Vertical Coordinate System Definition": "Placeholder text.",
    "Detailed Description": "Placeholder text.",
    "Overview Description": "Placeholder text.",
    "Data Custodian": "Placeholder text.",
    "Resource Description": "Placeholder text.",
    "Standard Order Process": "Placeholder text.",
    "Technical Prerequisites": "Placeholder text.",
    "Metadata Date": "Placeholder text.",
    "Metadata Standard Name": "Placeholder text.",
    "Metadata Standard Version": "Placeholder text.",
    "Metadata Time Conversion": "Placeholder text.",
    "Available in Platform": "Placeholder text.",
    "External Metadata Reference": "Placeholder text."
  },
  "Moreton Bay Marine Park Designated Areas": {
    "Citation": "� State of Queensland (Department of Environment and Science) 2023. Updated data available at http://qldspatial.information.qld.gov.au/catalogue//.",
    "Description": "Placeholder text.",
    "Time Period of Content": "03/12/2007-21/09/2010",
    "Spatial Domain": "Placeholder text.",
    "Keywords": "Placeholder text.",
    "Access Constraints": "Placeholder text.",
    "Use Constraints": "Placeholder text.",
    "Point of Contact": "Placeholder text.",
    "Browse Graphic": "Placeholder text.",
    "Data Set Credit - Where Credited": "Placeholder text.",
    "Data Set Size at Reception": "Placeholder text.",
    "Data Category": "Governance & Management",
    "Indirect Spatial Reference": "Placeholder text.",
    "Direct Spatial Reference": "Placeholder text.",
    "Point and Vector Object Information": "Placeholder text.",
    "Horizontal Coordinate System Definition": "Placeholder text.",
    "Vertical Coordinate System Definition": "Placeholder text.",
    "Detailed Description": "Placeholder text.",
    "Overview Description": "Placeholder text.",
    "Data Custodian": "Placeholder text.",
    "Resource Description": "Placeholder text.",
    "Standard Order Process": "Placeholder text.",
    "Technical Prerequisites": "Placeholder text.",
    "Metadata Date": "Placeholder text.",
    "Metadata Standard Name": "Placeholder text.",
    "Metadata Standard Version": "Placeholder text.",
    "Metadata Time Conversion": "Placeholder text.",
    "Available in Platform": "Placeholder text.",
    "External Metadata Reference": "Placeholder text."
  }
}
`;
