export var DataJson = `
{
  "Coral Classification Survey": {
    "Citation": "Placeholder text.",
    "Description": "Placeholder text.",
    "Time Period of Content": "1/1/2006 - 17/06/2023",
    "Spatial Domain": "Placeholder text.",
    "Keywords": "Placeholder text.",
    "Access Constraints": "Placeholder text.",
    "Use Constraints": "Placeholder text.",
    "Point of Contact": "Placeholder text.",
    "Browse Graphic": "Placeholder text.",
    "Data Set Credit - Where Credited": "Placeholder text.",
    "Data Set Size at Reception": "Placeholder text.",
    "Data Category": "Marine Life & Habitats",
    "Indirect Spatial Reference": "Placeholder text.",
    "Direct Spatial Reference": "Placeholder text.",
    "Point and Vector Object Information": "Placeholder text.",
    "Horizontal Coordinate System Definition": "Placeholder text.",
    "Vertical Coordinate System Definition": "Placeholder text.",
    "Detailed Description": "Placeholder text.",
    "Overview Description": "Placeholder text.",
    "Data Custodian": "Placeholder text.",
    "Resource Description": "Placeholder text.",
    "Standard Order Process": "Placeholder text.",
    "Technical Prerequisites": "Placeholder text.",
    "Metadata Date": "Placeholder text.",
    "Metadata Standard Name": "Placeholder text.",
    "Metadata Standard Version": "Placeholder text.",
    "Metadata Time Conversion": "Placeholder text.",
    "Available in Platform": "Placeholder text.",
    "External Metadata Reference": "Placeholder text."
  },
  "Fish & Invertebrate Abundance Survey": {
    "Citation": "Placeholder text.",
    "Description": "Placeholder text.",
    "Time Period of Content": "2007-2023",
    "Spatial Domain": "Placeholder text.",
    "Keywords": "Placeholder text.",
    "Access Constraints": "Placeholder text.",
    "Use Constraints": "Placeholder text.",
    "Point of Contact": "Placeholder text.",
    "Browse Graphic": "Placeholder text.",
    "Data Set Credit - Where Credited": "Placeholder text.",
    "Data Set Size at Reception": "Placeholder text.",
    "Data Category": "Marine Life & Habitats",
    "Indirect Spatial Reference": "Placeholder text.",
    "Direct Spatial Reference": "Placeholder text.",
    "Point and Vector Object Information": "Placeholder text.",
    "Horizontal Coordinate System Definition": "Placeholder text.",
    "Vertical Coordinate System Definition": "Placeholder text.",
    "Detailed Description": "Placeholder text.",
    "Overview Description": "Placeholder text.",
    "Data Custodian": "Placeholder text.",
    "Resource Description": "Placeholder text.",
    "Standard Order Process": "Placeholder text.",
    "Technical Prerequisites": "Placeholder text.",
    "Metadata Date": "Placeholder text.",
    "Metadata Standard Name": "Placeholder text.",
    "Metadata Standard Version": "Placeholder text.",
    "Metadata Time Conversion": "Placeholder text.",
    "Available in Platform": "Placeholder text.",
    "External Metadata Reference": "Placeholder text."
  },
  "Shipping and Boating Channels": {
    "Citation": "Placeholder text.",
    "Description": "Placeholder text.",
    "Time Period of Content": "2018",
    "Spatial Domain": "Placeholder text.",
    "Keywords": "Placeholder text.",
    "Access Constraints": "Placeholder text.",
    "Use Constraints": "Placeholder text.",
    "Point of Contact": "Placeholder text.",
    "Browse Graphic": "Placeholder text.",
    "Data Set Credit - Where Credited": "Placeholder text.",
    "Data Set Size at Reception": "Placeholder text.",
    "Data Category": "Human Use & Users",
    "Indirect Spatial Reference": "Placeholder text.",
    "Direct Spatial Reference": "Placeholder text.",
    "Point and Vector Object Information": "Placeholder text.",
    "Horizontal Coordinate System Definition": "Placeholder text.",
    "Vertical Coordinate System Definition": "Placeholder text.",
    "Detailed Description": "Placeholder text.",
    "Overview Description": "Placeholder text.",
    "Data Custodian": "Placeholder text.",
    "Resource Description": "Placeholder text.",
    "Standard Order Process": "Placeholder text.",
    "Technical Prerequisites": "Placeholder text.",
    "Metadata Date": "Placeholder text.",
    "Metadata Standard Name": "Placeholder text.",
    "Metadata Standard Version": "Placeholder text.",
    "Metadata Time Conversion": "Placeholder text.",
    "Available in Platform": "Placeholder text.",
    "External Metadata Reference": "Placeholder text."
  },
  "Boating Activity": {
    "Citation": "Placeholder text.",
    "Description": "Placeholder text.",
    "Time Period of Content": "23/07/2016 - 26/02/2023",
    "Spatial Domain": "Placeholder text.",
    "Keywords": "Placeholder text.",
    "Access Constraints": "Placeholder text.",
    "Use Constraints": "Placeholder text.",
    "Point of Contact": "Placeholder text.",
    "Browse Graphic": "Placeholder text.",
    "Data Set Credit - Where Credited": "Placeholder text.",
    "Data Set Size at Reception": "Placeholder text.",
    "Data Category": "Human Use & Users",
    "Indirect Spatial Reference": "Placeholder text.",
    "Direct Spatial Reference": "Placeholder text.",
    "Point and Vector Object Information": "Placeholder text.",
    "Horizontal Coordinate System Definition": "Placeholder text.",
    "Vertical Coordinate System Definition": "Placeholder text.",
    "Detailed Description": "Placeholder text.",
    "Overview Description": "Placeholder text.",
    "Data Custodian": "Placeholder text.",
    "Resource Description": "Placeholder text.",
    "Standard Order Process": "Placeholder text.",
    "Technical Prerequisites": "Placeholder text.",
    "Metadata Date": "Placeholder text.",
    "Metadata Standard Name": "Placeholder text.",
    "Metadata Standard Version": "Placeholder text.",
    "Metadata Time Conversion": "Placeholder text.",
    "Available in Platform": "Placeholder text.",
    "External Metadata Reference": "Placeholder text."
  },
  "Moreton Bay Social Values Survey": {
    "Citation": "Placeholder text.",
    "Description": "Placeholder text.",
    "Time Period of Content": "2023",
    "Spatial Domain": "Placeholder text.",
    "Keywords": "Placeholder text.",
    "Access Constraints": "Placeholder text.",
    "Use Constraints": "Placeholder text.",
    "Point of Contact": "Placeholder text.",
    "Browse Graphic": "Placeholder text.",
    "Data Set Credit - Where Credited": "Placeholder text.",
    "Data Set Size at Reception": "Placeholder text.",
    "Data Category": "Human Use & Users",
    "Indirect Spatial Reference": "Placeholder text.",
    "Direct Spatial Reference": "Placeholder text.",
    "Point and Vector Object Information": "Placeholder text.",
    "Horizontal Coordinate System Definition": "Placeholder text.",
    "Vertical Coordinate System Definition": "Placeholder text.",
    "Detailed Description": "Placeholder text.",
    "Overview Description": "Placeholder text.",
    "Data Custodian": "Placeholder text.",
    "Resource Description": "Placeholder text.",
    "Standard Order Process": "Placeholder text.",
    "Technical Prerequisites": "Placeholder text.",
    "Metadata Date": "Placeholder text.",
    "Metadata Standard Name": "Placeholder text.",
    "Metadata Standard Version": "Placeholder text.",
    "Metadata Time Conversion": "Placeholder text.",
    "Available in Platform": "Placeholder text.",
    "External Metadata Reference": "Placeholder text."
  },
  "Seagrass Extent Map 2004": {
    "Citation": "Placeholder text.",
    "Description": "Placeholder text.",
    "Time Period of Content": "2004",
    "Spatial Domain": "Placeholder text.",
    "Keywords": "Placeholder text.",
    "Access Constraints": "Placeholder text.",
    "Use Constraints": "Placeholder text.",
    "Point of Contact": "Placeholder text.",
    "Browse Graphic": "Placeholder text.",
    "Data Set Credit - Where Credited": "Placeholder text.",
    "Data Set Size at Reception": "Placeholder text.",
    "Data Category": "Marine Life & Habitats",
    "Indirect Spatial Reference": "Placeholder text.",
    "Direct Spatial Reference": "Placeholder text.",
    "Point and Vector Object Information": "Placeholder text.",
    "Horizontal Coordinate System Definition": "Placeholder text.",
    "Vertical Coordinate System Definition": "Placeholder text.",
    "Detailed Description": "Placeholder text.",
    "Overview Description": "Placeholder text.",
    "Data Custodian": "Placeholder text.",
    "Resource Description": "Placeholder text.",
    "Standard Order Process": "Placeholder text.",
    "Technical Prerequisites": "Placeholder text.",
    "Metadata Date": "Placeholder text.",
    "Metadata Standard Name": "Placeholder text.",
    "Metadata Standard Version": "Placeholder text.",
    "Metadata Time Conversion": "Placeholder text.",
    "Available in Platform": "Placeholder text.",
    "External Metadata Reference": "Placeholder text."
  },
  "Seagrass Extent Map 2011": {
    "Citation": "Placeholder text.",
    "Description": "Placeholder text.",
    "Time Period of Content": "2011",
    "Spatial Domain": "Placeholder text.",
    "Keywords": "Placeholder text.",
    "Access Constraints": "Placeholder text.",
    "Use Constraints": "Placeholder text.",
    "Point of Contact": "Placeholder text.",
    "Browse Graphic": "Placeholder text.",
    "Data Set Credit - Where Credited": "Placeholder text.",
    "Data Set Size at Reception": "Placeholder text.",
    "Data Category": "Marine Life & Habitats",
    "Indirect Spatial Reference": "Placeholder text.",
    "Direct Spatial Reference": "Placeholder text.",
    "Point and Vector Object Information": "Placeholder text.",
    "Horizontal Coordinate System Definition": "Placeholder text.",
    "Vertical Coordinate System Definition": "Placeholder text.",
    "Detailed Description": "Placeholder text.",
    "Overview Description": "Placeholder text.",
    "Data Custodian": "Placeholder text.",
    "Resource Description": "Placeholder text.",
    "Standard Order Process": "Placeholder text.",
    "Technical Prerequisites": "Placeholder text.",
    "Metadata Date": "Placeholder text.",
    "Metadata Standard Name": "Placeholder text.",
    "Metadata Standard Version": "Placeholder text.",
    "Metadata Time Conversion": "Placeholder text.",
    "Available in Platform": "Placeholder text.",
    "External Metadata Reference": "Placeholder text."
  },
  "Seagrass Extent Map 2015": {
    "Citation": "Placeholder text.",
    "Description": "Placeholder text.",
    "Time Period of Content": "2015",
    "Spatial Domain": "Placeholder text.",
    "Keywords": "Placeholder text.",
    "Access Constraints": "Placeholder text.",
    "Use Constraints": "Placeholder text.",
    "Point of Contact": "Placeholder text.",
    "Browse Graphic": "Placeholder text.",
    "Data Set Credit - Where Credited": "Placeholder text.",
    "Data Set Size at Reception": "Placeholder text.",
    "Data Category": "Marine Life & Habitats",
    "Indirect Spatial Reference": "Placeholder text.",
    "Direct Spatial Reference": "Placeholder text.",
    "Point and Vector Object Information": "Placeholder text.",
    "Horizontal Coordinate System Definition": "Placeholder text.",
    "Vertical Coordinate System Definition": "Placeholder text.",
    "Detailed Description": "Placeholder text.",
    "Overview Description": "Placeholder text.",
    "Data Custodian": "Placeholder text.",
    "Resource Description": "Placeholder text.",
    "Standard Order Process": "Placeholder text.",
    "Technical Prerequisites": "Placeholder text.",
    "Metadata Date": "Placeholder text.",
    "Metadata Standard Name": "Placeholder text.",
    "Metadata Standard Version": "Placeholder text.",
    "Metadata Time Conversion": "Placeholder text.",
    "Available in Platform": "Placeholder text.",
    "External Metadata Reference": "Placeholder text."
  },
  "Wetland Extent Classifications": {
    "Citation": "Placeholder text.",
    "Description": "Placeholder text.",
    "Time Period of Content": "16/07/2007",
    "Spatial Domain": "Placeholder text.",
    "Keywords": "Placeholder text.",
    "Access Constraints": "Placeholder text.",
    "Use Constraints": "Placeholder text.",
    "Point of Contact": "Placeholder text.",
    "Browse Graphic": "Placeholder text.",
    "Data Set Credit - Where Credited": "Placeholder text.",
    "Data Set Size at Reception": "Placeholder text.",
    "Data Category": "Marine Life & Habitats",
    "Indirect Spatial Reference": "Placeholder text.",
    "Direct Spatial Reference": "Placeholder text.",
    "Point and Vector Object Information": "Placeholder text.",
    "Horizontal Coordinate System Definition": "Placeholder text.",
    "Vertical Coordinate System Definition": "Placeholder text.",
    "Detailed Description": "Placeholder text.",
    "Overview Description": "Placeholder text.",
    "Data Custodian": "Placeholder text.",
    "Resource Description": "Placeholder text.",
    "Standard Order Process": "Placeholder text.",
    "Technical Prerequisites": "Placeholder text.",
    "Metadata Date": "Placeholder text.",
    "Metadata Standard Name": "Placeholder text.",
    "Metadata Standard Version": "Placeholder text.",
    "Metadata Time Conversion": "Placeholder text.",
    "Available in Platform": "Placeholder text.",
    "External Metadata Reference": "Placeholder text."
  },
  "Satellite Mosaic of Moreton Bay 2018": {
    "Citation": "Placeholder text.",
    "Description": "Placeholder text.",
    "Time Period of Content": "2018",
    "Spatial Domain": "Placeholder text.",
    "Keywords": "Placeholder text.",
    "Access Constraints": "Placeholder text.",
    "Use Constraints": "Placeholder text.",
    "Point of Contact": "Placeholder text.",
    "Browse Graphic": "Placeholder text.",
    "Data Set Credit - Where Credited": "Placeholder text.",
    "Data Set Size at Reception": "Placeholder text.",
    "Data Category": "Environmental Change & Monitoring",
    "Indirect Spatial Reference": "Placeholder text.",
    "Direct Spatial Reference": "Placeholder text.",
    "Point and Vector Object Information": "Placeholder text.",
    "Horizontal Coordinate System Definition": "Placeholder text.",
    "Vertical Coordinate System Definition": "Placeholder text.",
    "Detailed Description": "Placeholder text.",
    "Overview Description": "Placeholder text.",
    "Data Custodian": "Placeholder text.",
    "Resource Description": "Placeholder text.",
    "Standard Order Process": "Placeholder text.",
    "Technical Prerequisites": "Placeholder text.",
    "Metadata Date": "Placeholder text.",
    "Metadata Standard Name": "Placeholder text.",
    "Metadata Standard Version": "Placeholder text.",
    "Metadata Time Conversion": "Placeholder text.",
    "Available in Platform": "Placeholder text.",
    "External Metadata Reference": "Placeholder text."
  },
  "Satellite Mosaic of Moreton Bay 2019": {
    "Citation": "Placeholder text.",
    "Description": "Placeholder text.",
    "Time Period of Content": "2019",
    "Spatial Domain": "Placeholder text.",
    "Keywords": "Placeholder text.",
    "Access Constraints": "Placeholder text.",
    "Use Constraints": "Placeholder text.",
    "Point of Contact": "Placeholder text.",
    "Browse Graphic": "Placeholder text.",
    "Data Set Credit - Where Credited": "Placeholder text.",
    "Data Set Size at Reception": "Placeholder text.",
    "Data Category": "Environmental Change & Monitoring",
    "Indirect Spatial Reference": "Placeholder text.",
    "Direct Spatial Reference": "Placeholder text.",
    "Point and Vector Object Information": "Placeholder text.",
    "Horizontal Coordinate System Definition": "Placeholder text.",
    "Vertical Coordinate System Definition": "Placeholder text.",
    "Detailed Description": "Placeholder text.",
    "Overview Description": "Placeholder text.",
    "Data Custodian": "Placeholder text.",
    "Resource Description": "Placeholder text.",
    "Standard Order Process": "Placeholder text.",
    "Technical Prerequisites": "Placeholder text.",
    "Metadata Date": "Placeholder text.",
    "Metadata Standard Name": "Placeholder text.",
    "Metadata Standard Version": "Placeholder text.",
    "Metadata Time Conversion": "Placeholder text.",
    "Available in Platform": "Placeholder text.",
    "External Metadata Reference": "Placeholder text."
  },
  "Satellite Mosaic of Moreton Bay 2020": {
    "Citation": "Placeholder text.",
    "Description": "Placeholder text.",
    "Time Period of Content": "2020",
    "Spatial Domain": "Placeholder text.",
    "Keywords": "Placeholder text.",
    "Access Constraints": "Placeholder text.",
    "Use Constraints": "Placeholder text.",
    "Point of Contact": "Placeholder text.",
    "Browse Graphic": "Placeholder text.",
    "Data Set Credit - Where Credited": "Placeholder text.",
    "Data Set Size at Reception": "Placeholder text.",
    "Data Category": "Environmental Change & Monitoring",
    "Indirect Spatial Reference": "Placeholder text.",
    "Direct Spatial Reference": "Placeholder text.",
    "Point and Vector Object Information": "Placeholder text.",
    "Horizontal Coordinate System Definition": "Placeholder text.",
    "Vertical Coordinate System Definition": "Placeholder text.",
    "Detailed Description": "Placeholder text.",
    "Overview Description": "Placeholder text.",
    "Data Custodian": "Placeholder text.",
    "Resource Description": "Placeholder text.",
    "Standard Order Process": "Placeholder text.",
    "Technical Prerequisites": "Placeholder text.",
    "Metadata Date": "Placeholder text.",
    "Metadata Standard Name": "Placeholder text.",
    "Metadata Standard Version": "Placeholder text.",
    "Metadata Time Conversion": "Placeholder text.",
    "Available in Platform": "Placeholder text.",
    "External Metadata Reference": "Placeholder text."
  },
  "Reef Extent Map": {
    "Citation": "Placeholder text.",
    "Description": "Placeholder text.",
    "Time Period of Content": "2014",
    "Spatial Domain": "Placeholder text.",
    "Keywords": "Placeholder text.",
    "Access Constraints": "Placeholder text.",
    "Use Constraints": "Placeholder text.",
    "Point of Contact": "Placeholder text.",
    "Browse Graphic": "Placeholder text.",
    "Data Set Credit - Where Credited": "Placeholder text.",
    "Data Set Size at Reception": "Placeholder text.",
    "Data Category": "Marine Life & Habitats",
    "Indirect Spatial Reference": "Placeholder text.",
    "Direct Spatial Reference": "Placeholder text.",
    "Point and Vector Object Information": "Placeholder text.",
    "Horizontal Coordinate System Definition": "Placeholder text.",
    "Vertical Coordinate System Definition": "Placeholder text.",
    "Detailed Description": "Placeholder text.",
    "Overview Description": "Placeholder text.",
    "Data Custodian": "Placeholder text.",
    "Resource Description": "Placeholder text.",
    "Standard Order Process": "Placeholder text.",
    "Technical Prerequisites": "Placeholder text.",
    "Metadata Date": "Placeholder text.",
    "Metadata Standard Name": "Placeholder text.",
    "Metadata Standard Version": "Placeholder text.",
    "Metadata Time Conversion": "Placeholder text.",
    "Available in Platform": "Placeholder text.",
    "External Metadata Reference": "Placeholder text."
  },
  "Benthic Inventory of Moreton Bay Reefs": {
    "Citation": "Placeholder text.",
    "Description": "Placeholder text.",
    "Time Period of Content": "2016",
    "Spatial Domain": "Placeholder text.",
    "Keywords": "Placeholder text.",
    "Access Constraints": "Placeholder text.",
    "Use Constraints": "Placeholder text.",
    "Point of Contact": "Placeholder text.",
    "Browse Graphic": "Placeholder text.",
    "Data Set Credit - Where Credited": "Placeholder text.",
    "Data Set Size at Reception": "Placeholder text.",
    "Data Category": "Marine Life & Habitats",
    "Indirect Spatial Reference": "Placeholder text.",
    "Direct Spatial Reference": "Placeholder text.",
    "Point and Vector Object Information": "Placeholder text.",
    "Horizontal Coordinate System Definition": "Placeholder text.",
    "Vertical Coordinate System Definition": "Placeholder text.",
    "Detailed Description": "Placeholder text.",
    "Overview Description": "Placeholder text.",
    "Data Custodian": "Placeholder text.",
    "Resource Description": "Placeholder text.",
    "Standard Order Process": "Placeholder text.",
    "Technical Prerequisites": "Placeholder text.",
    "Metadata Date": "Placeholder text.",
    "Metadata Standard Name": "Placeholder text.",
    "Metadata Standard Version": "Placeholder text.",
    "Metadata Time Conversion": "Placeholder text.",
    "Available in Platform": "Placeholder text.",
    "External Metadata Reference": "Placeholder text."
  },
  "Marine Acoustic Telemetry Data": {
    "Citation": "Placeholder text.",
    "Description": "Placeholder text.",
    "Time Period of Content": "2009-2015",
    "Spatial Domain": "Placeholder text.",
    "Keywords": "Placeholder text.",
    "Access Constraints": "Placeholder text.",
    "Use Constraints": "Placeholder text.",
    "Point of Contact": "Placeholder text.",
    "Browse Graphic": "Placeholder text.",
    "Data Set Credit - Where Credited": "Placeholder text.",
    "Data Set Size at Reception": "Placeholder text.",
    "Data Category": "Marine Life & Habitats",
    "Indirect Spatial Reference": "Placeholder text.",
    "Direct Spatial Reference": "Placeholder text.",
    "Point and Vector Object Information": "Placeholder text.",
    "Horizontal Coordinate System Definition": "Placeholder text.",
    "Vertical Coordinate System Definition": "Placeholder text.",
    "Detailed Description": "Placeholder text.",
    "Overview Description": "Placeholder text.",
    "Data Custodian": "Placeholder text.",
    "Resource Description": "Placeholder text.",
    "Standard Order Process": "Placeholder text.",
    "Technical Prerequisites": "Placeholder text.",
    "Metadata Date": "Placeholder text.",
    "Metadata Standard Name": "Placeholder text.",
    "Metadata Standard Version": "Placeholder text.",
    "Metadata Time Conversion": "Placeholder text.",
    "Available in Platform": "Placeholder text.",
    "External Metadata Reference": "Placeholder text."
  },
  "Moreton Bay Broadscale Habitats": {
    "Citation": "Placeholder text.",
    "Description": "Placeholder text.",
    "Time Period of Content": "12/09/2007-02/12/2007",
    "Spatial Domain": "Placeholder text.",
    "Keywords": "Placeholder text.",
    "Access Constraints": "Placeholder text.",
    "Use Constraints": "Placeholder text.",
    "Point of Contact": "Placeholder text.",
    "Browse Graphic": "Placeholder text.",
    "Data Set Credit - Where Credited": "Placeholder text.",
    "Data Set Size at Reception": "Placeholder text.",
    "Data Category": "Marine Life & Habitats",
    "Indirect Spatial Reference": "Placeholder text.",
    "Direct Spatial Reference": "Placeholder text.",
    "Point and Vector Object Information": "Placeholder text.",
    "Horizontal Coordinate System Definition": "Placeholder text.",
    "Vertical Coordinate System Definition": "Placeholder text.",
    "Detailed Description": "Placeholder text.",
    "Overview Description": "Placeholder text.",
    "Data Custodian": "Placeholder text.",
    "Resource Description": "Placeholder text.",
    "Standard Order Process": "Placeholder text.",
    "Technical Prerequisites": "Placeholder text.",
    "Metadata Date": "Placeholder text.",
    "Metadata Standard Name": "Placeholder text.",
    "Metadata Standard Version": "Placeholder text.",
    "Metadata Time Conversion": "Placeholder text.",
    "Available in Platform": "Placeholder text.",
    "External Metadata Reference": "Placeholder text."
  },
  "Moreton Bay Marine Park Zoning": {
    "Citation": "Placeholder text.",
    "Description": "Placeholder text.",
    "Time Period of Content": "03/12/2007-01/03/2009",
    "Spatial Domain": "Placeholder text.",
    "Keywords": "Placeholder text.",
    "Access Constraints": "Placeholder text.",
    "Use Constraints": "Placeholder text.",
    "Point of Contact": "Placeholder text.",
    "Browse Graphic": "Placeholder text.",
    "Data Set Credit - Where Credited": "Placeholder text.",
    "Data Set Size at Reception": "Placeholder text.",
    "Data Category": "Governance & Management",
    "Indirect Spatial Reference": "Placeholder text.",
    "Direct Spatial Reference": "Placeholder text.",
    "Point and Vector Object Information": "Placeholder text.",
    "Horizontal Coordinate System Definition": "Placeholder text.",
    "Vertical Coordinate System Definition": "Placeholder text.",
    "Detailed Description": "Placeholder text.",
    "Overview Description": "Placeholder text.",
    "Data Custodian": "Placeholder text.",
    "Resource Description": "Placeholder text.",
    "Standard Order Process": "Placeholder text.",
    "Technical Prerequisites": "Placeholder text.",
    "Metadata Date": "Placeholder text.",
    "Metadata Standard Name": "Placeholder text.",
    "Metadata Standard Version": "Placeholder text.",
    "Metadata Time Conversion": "Placeholder text.",
    "Available in Platform": "Placeholder text.",
    "External Metadata Reference": "Placeholder text."
  },
  "Moreton Bay Marine Park Boundary": {
    "Citation": "Placeholder text.",
    "Description": "Placeholder text.",
    "Time Period of Content": "16/07/2007",
    "Spatial Domain": "Placeholder text.",
    "Keywords": "Placeholder text.",
    "Access Constraints": "Placeholder text.",
    "Use Constraints": "Placeholder text.",
    "Point of Contact": "Placeholder text.",
    "Browse Graphic": "Placeholder text.",
    "Data Set Credit - Where Credited": "Placeholder text.",
    "Data Set Size at Reception": "Placeholder text.",
    "Data Category": "Governance & Management",
    "Indirect Spatial Reference": "Placeholder text.",
    "Direct Spatial Reference": "Placeholder text.",
    "Point and Vector Object Information": "Placeholder text.",
    "Horizontal Coordinate System Definition": "Placeholder text.",
    "Vertical Coordinate System Definition": "Placeholder text.",
    "Detailed Description": "Placeholder text.",
    "Overview Description": "Placeholder text.",
    "Data Custodian": "Placeholder text.",
    "Resource Description": "Placeholder text.",
    "Standard Order Process": "Placeholder text.",
    "Technical Prerequisites": "Placeholder text.",
    "Metadata Date": "Placeholder text.",
    "Metadata Standard Name": "Placeholder text.",
    "Metadata Standard Version": "Placeholder text.",
    "Metadata Time Conversion": "Placeholder text.",
    "Available in Platform": "Placeholder text.",
    "External Metadata Reference": "Placeholder text."
  },
  "Moreton Bay Marine Park Designated Areas": {
    "Citation": "Placeholder text.",
    "Description": "Placeholder text.",
    "Time Period of Content": "03/12/2007-21/09/2010",
    "Spatial Domain": "Placeholder text.",
    "Keywords": "Placeholder text.",
    "Access Constraints": "Placeholder text.",
    "Use Constraints": "Placeholder text.",
    "Point of Contact": "Placeholder text.",
    "Browse Graphic": "Placeholder text.",
    "Data Set Credit - Where Credited": "Placeholder text.",
    "Data Set Size at Reception": "Placeholder text.",
    "Data Category": "Governance & Management",
    "Indirect Spatial Reference": "Placeholder text.",
    "Direct Spatial Reference": "Placeholder text.",
    "Point and Vector Object Information": "Placeholder text.",
    "Horizontal Coordinate System Definition": "Placeholder text.",
    "Vertical Coordinate System Definition": "Placeholder text.",
    "Detailed Description": "Placeholder text.",
    "Overview Description": "Placeholder text.",
    "Data Custodian": "Placeholder text.",
    "Resource Description": "Placeholder text.",
    "Standard Order Process": "Placeholder text.",
    "Technical Prerequisites": "Placeholder text.",
    "Metadata Date": "Placeholder text.",
    "Metadata Standard Name": "Placeholder text.",
    "Metadata Standard Version": "Placeholder text.",
    "Metadata Time Conversion": "Placeholder text.",
    "Available in Platform": "Placeholder text.",
    "External Metadata Reference": "Placeholder text."
  }
}
`;
